version: '3.8'

services:
  web_page_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitoring

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - monitoring

networks:
  monitoring:
