### Missing URL in the request
POST http://localhost:8080/analyzer
Content-Type: application/json

### Empty URL in the request
POST http://localhost:8080/analyzer
Content-Type: application/json

{
"webpageUrl": " "
}
### Valid URL in the request
POST http://localhost:8080/analyzer
Content-Type: application/json

{
"webpageUrl": "https://medium.com/@maciek.pilot2/golang-project-structure-b88327220d73"
}

###